services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${MY_UID}:${MY_GID}"
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=512MB'
    networks:
      - monitoring-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${MY_UID}:${MY_GID}"
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - monitoring-network
    restart: unless-stopped
    environment:
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SERVER_ROOT_URL=https://${DOMAIN}

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitoring-network

volumes:
  caddy_data:
  caddy_config:

networks:
  monitoring-network:
    driver: bridge